spring:
  datasource:
    initialization-mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  data:
    rest:
      base-path: /datarest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: "logs/application.log"