drop table IF EXISTS BOOKS;
create TABLE BOOKS(ID BIGINT PRIMARY KEY, NAME VARCHAR(255), AUTHOR_ID BIGINT, GENRE_ID BIGINT);

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID BIGINT PRIMARY KEY, NAME VARCHAR(255));

drop table IF EXISTS GENRES;
create TABLE GENRES(ID BIGINT PRIMARY KEY, GENRE VARCHAR(255));